### ISSUE TITLE
BUG0001

### ISSUE THREAD

**Issue by smpawar** [smpawar/testrepo2#2]
## Todo

- [x] Write an API
- [x] Test the code
- [x] Check all the boxes
